### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by OccultWarlock** [statping-ng/statping-ng#118]
No new version in about 6 months 😞

**Comment by jemand771** [comment]
the latest (pre-)release is [dev-v0.90.80](https://github.com/statping-ng/statping-ng/releases/tag/dev-v0.90.80)
feature-wise, it's [the same as dev](https://github.com/statping-ng/statping-ng/compare/dev-v0.90.80...statping-ng:dev) and contains [all changes here](https://github.com/statping/statping/compare/dev...statping-ng:dev-v0.90.80) that differ from the original repo

on more automated/frequent releases: we're partially held up by #17 (my bad), but there aren't any new code changes anyway. if you have a feature in mind, feel free to open an issue about it. even better, PR it if you can :)
we'll do our best to address incoming PRs but don't really have the time/skill to work on the code ourselves

**Comment by OccultWarlock** [comment]
@jemand771 im wondering if it would be possible to build this with Cloudflare Pages (https://pages.cloudflare.com), setting the database to my local server?

That might be neat

**Comment by jemand771** [comment]
I don't think using cf pages is possible at the moment as the frontend (which you could theoretically host on cf) is integrated tightly into the backend: [frontend/vue.config.js](https://github.com/statping-ng/statping-ng/blob/dev/frontend/vue.config.js) | [handlers/routes.go](https://github.com/statping-ng/statping-ng/blob/dev/handlers/routes.go)

again, I don't really use any of those technologies (including cf pages), so someone with more experience might find a way

on the upside, hosting just the frontend using cloudflare with the backend/db being one some server you control doesn't make much sense anyway. you won't get any high availability (at least not for the backend, which is argualy the important part) and while initial asset loading will be faster due to cf caching, api requests might take longer since the api server is.. [somewhere else].
if you want cloudflare's ddos protection features and whatnot, use their dns proxying.

**Comment by OccultWarlock** [comment]
Got it - I’m just having incredibly ssssslllllloooowwww load times while running this off my raspberry pi 4, and im not sure how to tweak it to make it run faster. You can see @ https://monitor.noff.co vs https://status.noff.co (I moved the status site over to https://Fly.IO and it drastically decreased the load time

**Comment by adamboutcher** [comment]
There's a new [stable build](https://github.com/statping-ng/statping-ng/releases/tag/v0.90.80) today, so I'm going to close this issue off.
I suspect your slowness is down to disk IO, especially if your using the default SQLite and lots of frequent checks.
