### ISSUE TITLE
How should checkins work?

### ISSUE THREAD

**Issue by fluential** [statping-ng/statping-ng#147]
If I create Static Service type and feed regular checks via checking - should this service go green at some point?

**Comment by adamboutcher** [comment]
I believe so but iirc people have mentioned that checkins don't work as we expect.

**Comment by jemand771** [comment]
alright, checkins are super broken. since we already have #16 for that, I'd like to track any new findings there.
in short: successful checkins don't affect the service itself, and (at least for me rn) a checkin doesn't to red again if it was green once

to answer your question: yes, in theory, creating a static service and checkin is the way to go here. it just doesn't work right now D:
