### ISSUE TITLE
Database size requirement

### ISSUE THREAD

**Issue by capriciousduck** [statping-ng/statping-ng#92]
Hi.

I wanted to use Heroku's 1GB PostgreSQL. Would it be enough?

**Comment by jemand771** [comment]
I can't really give you a definitive answer on this for the long run, but it will be enough to get started.
The database will slowly & steadily grow as statping collects metrics. I'm not sure if old data gets purged. If not, you might have to do that manually after a while.

From my (really crude) test setup using sqlite and the 6 default services:
Initial DB size: 5336 KiB
Size increase after 1 hour: +104 KiB
This means that when monitoring 10 services, that gigabyte of storage should last you at least 9 months.
<details>
<summary>math (click to expand)</summary>

please double-check this, it's possible I've made a mistake somewhere.
104 KiB for 1 hour with 7 services
104 KiB = 104 * 1024 / 1000 KB = 106.5 KB
1 GB (10^6 KB) / (106.5 KB / hour) = 9390 hours
1 service: 9390 hours * 7 = 65,730 hours
convert unit: -> 2739  days or 391 weeks or 90 months or 7.5 years
finally divide by number of services to get expected time (estimate)
</details>

Please note that
1. postgres probably needs less space than mysql due to compression
2. most of the services were failing, and fails are technically bigger than hits. in a realistic setup, there won't be as many failures
3. manually created incidents and notifiers take up extra space, but that doesn't really matter for the same reason as 2.

so you'll get even more out of your 1GB!

Since my test setup is very different from what you'd actually use, I can't tell you how much I'm off. Maybe someone from the community has data to add here ^^

**Comment by capriciousduck** [comment]
Thanks for the example. I don't need metric logs for a long time. Is it possible to delete them after a given time?

**Comment by jemand771** [comment]
You could always go in and delete some entries in the database yourself, namely from the `hits` and `failures` tables. I don't know what kinds of DB access heroku gives you (webinterface or just DB shell)

something like
```
delete from hits where created_at < date('now', '-30 day');
delete from failures where created_at < date('now', '-30 day');
```
will delete all hits and failures excluding the last 30 days. you can change the duration to your liking (don't forget the `-`, otherwise it'll delete everything. use transactions if you're unsure)

Adding something like a "purge records before date X" button to the settings menu could be useful though
(note that we're not go devs and rely on the community for contributions, so this might take a while)

**Comment by capriciousduck** [comment]
Is there an environment variable for setting the duration?

**Comment by jemand771** [comment]
I don't think there's any statping-native way to do it, at least not yet

**Comment by capriciousduck** [comment]
I've looked into the documentation and found this env variable: 

REMOVE_AFTER - Automatically delete records after time (default 3 months, '12h = 12 hours')

What does this mean? What records? Not the hits and fails?

**Comment by jemand771** [comment]
oh yeah, you're right :) I should have searched more thoroughly

there's `REMOVE_AFTER` and `CLEANUP_INTERVAL` to control the deletion behaviour. this will remove all hits and failures older than `REMOVE_AFTER` (default: 90 days) every `CLEANUP_INTERVAL` (default: 1 hour)

**Comment by capriciousduck** [comment]
So by default statping check whether the records are 90 days older every one hour. Am I right?

**Comment by jemand771** [comment]
I don't have any tests to confirm that this works, but it should_, yeah

**Comment by adamboutcher** [comment]
Are we ok to close this off @capriciousduck ?

**Comment by capriciousduck** [comment]
Yes. You can close this issue. Thanks.
